spring.application.name=api-biblioteca

# Conexão com o PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bibliotecadb}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.username=${DB_USERNAME:postgres}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect